name: Generate Terraform Docs

on:
  workflow_call:

permissions:
  repository-projects: write
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write

jobs:
  reusable-docs-wf:
    runs-on: ubuntu-latest  # Run the workflow on an Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Setup Terraform Docs  
        uses: terraform-docs/gh-actions@v1.0.0   # Action to generate Terraform documentation
        with:
          working-dir: .                 # Use the current directory
          output-file: README.md        # Output README file
          output-method: inject         # Inject into README
          git-push: "true"              # Automatically push the changes
